export const SORTING_TYPE = 'SORTING_TYPE';
export const SORTING_ORDER = 'SORTING_ORDER';
export const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE';
export const FILTERING_COUNTRY = 'FILTERING_COUNTRY';
export const FILTERING_HEIGHT = 'FILTERING_HEIGHT';
export const FILTERING_RATING = 'FILTERING_RATING';